# Generated by Django 4.2.14 on 2024-07-20 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_noteboard_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='member_image',
            field=models.ImageField(blank=True, upload_to='profile_pics'),
        ),
    ]
