# Generated by Django 4.2.14 on 2024-07-21 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test_noteboard_app', '0003_post'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='author',
            new_name='member',
        ),
    ]
