# Generated by Django 4.2.5 on 2024-08-07 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test_noteboard_app', '0005_like'),
    ]

    operations = [
        migrations.RenameField(
            model_name='like',
            old_name='user',
            new_name='member',
        ),
        migrations.AlterUniqueTogether(
            name='like',
            unique_together={('member', 'post')},
        ),
    ]
