# Generated by Django 4.2.5 on 2024-08-14 04:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_noteboard_app', '0007_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='followers',
            field=models.ManyToManyField(related_name='following', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='member',
            name='only_followers_flg',
            field=models.BooleanField(default=False),
        ),
    ]
